# Generated by Django 4.2.3 on 2023-08-02 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Tytuł')),
                ('dishPicture', models.ImageField(blank=True, upload_to='dishPics', verbose_name='Zdjęcie potrawy')),
                ('myRating', models.CharField(choices=[('', 'Wybierz ocenę'), ('rew', 'Rewelacja'), ('nie', 'Nie do powtórzenia'), ('mod', 'Do modyfikacji')], default='', max_length=3)),
                ('descRecipe', models.TextField(blank=True)),
                ('webRecipe', models.URLField(blank=True)),
                ('picRecipe', models.ImageField(blank=True, upload_to='')),
                ('comment', models.TextField(blank=True)),
                ('mainComponets', models.TextField(blank=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-createDate',),
            },
        ),
    ]
