# Generated by Django 4.2.3 on 2023-09-06 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł')),
                ('slug', models.SlugField(max_length=100)),
                ('dish_picture', models.ImageField(blank=True, upload_to='dishPics', verbose_name='Zdjęcie potrawy')),
                ('my_rating', models.CharField(choices=[('', 'Wybierz ocenę'), ('REWELACJA', 'Rewelacja'), ('NIE DO POWTÓRZENIA', 'Nie do powtórzenia'), ('DO MODYFIKACJI', 'Do modyfikacji')], default='', max_length=20, verbose_name='Moja ocena')),
                ('desc_recipe', models.TextField(blank=True, verbose_name='Przepis')),
                ('web_recipe', models.URLField(blank=True, verbose_name='Strona www')),
                ('pic_recipe', models.ImageField(blank=True, upload_to='recipePics', verbose_name='Zdjęcie przepisu')),
                ('comment', models.TextField(blank=True, verbose_name='Moje uwagi')),
                ('main_components', models.TextField(blank=True, verbose_name='Główne składniki')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='cookMe.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='cookMe_cate_name_55234e_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['id', 'slug'], name='cookMe_reci_id_3f3563_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['title'], name='cookMe_reci_title_5941a6_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-create_date'], name='cookMe_reci_create__befbda_idx'),
        ),
    ]
