# Generated by Django 4.2.3 on 2023-08-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookMe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Moje uwagi'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='descRecipe',
            field=models.TextField(blank=True, verbose_name='Przepis'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='mainComponets',
            field=models.TextField(blank=True, verbose_name='Główne składniki'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='myRating',
            field=models.CharField(choices=[('', 'Wybierz ocenę'), ('rew', 'Rewelacja'), ('nie', 'Nie do powtórzenia'), ('mod', 'Do modyfikacji')], default='', max_length=3, verbose_name='Moja ocena'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picRecipe',
            field=models.ImageField(blank=True, upload_to='RecipePics', verbose_name='Zdjęcie przepisu'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='webRecipe',
            field=models.URLField(blank=True, verbose_name='Strona www'),
        ),
    ]
