# Generated by Django 4.2.3 on 2023-08-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookMe', '0002_alter_recipe_comment_alter_recipe_descrecipe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='mainComponets',
            new_name='mainComponents',
        ),
    ]
