# Generated by Django 4.2.3 on 2023-09-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookMe', '0002_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='desc_recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='dish_picture',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='main_components',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='my_rating',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='pic_recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='web_recipe',
        ),
    ]
