# Generated by Django 4.2.3 on 2023-09-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookMe', '0003_remove_recipe_comment_remove_recipe_desc_recipe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='cookMe_reci_title_5941a6_idx',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='recipe',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Moje uwagi'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='desc_recipe',
            field=models.TextField(blank=True, verbose_name='Przepis'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='dish_picture',
            field=models.ImageField(blank=True, upload_to='dishPics', verbose_name='Zdjęcie potrawy'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='main_components',
            field=models.TextField(blank=True, verbose_name='Główne składniki'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='my_rating',
            field=models.CharField(choices=[('', 'Wybierz ocenę'), ('rew', 'Rewelacja'), ('nie', 'Nie do powtórzenia'), ('mod', 'Do modyfikacji')], default='', max_length=3, verbose_name='Moja ocena'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='pic_recipe',
            field=models.ImageField(blank=True, upload_to='recipePics', verbose_name='Zdjęcie przepisu'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='web_recipe',
            field=models.URLField(blank=True, verbose_name='Strona www'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['name'], name='cookMe_reci_name_a3d695_idx'),
        ),
    ]
