# Generated by Django 4.2.3 on 2023-08-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookMe', '0004_alter_recipe_picrecipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-create_date',)},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='createDate',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='descRecipe',
            new_name='desc_recipe',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='dishPicture',
            new_name='dish_picture',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='mainComponents',
            new_name='main_components',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='myRating',
            new_name='my_rating',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='webRecipe',
            new_name='web_recipe',
        ),
    ]
