# Generated by Django 4.2.3 on 2023-08-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookMe', '0005_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='picRecipe',
            new_name='pic_recipe',
        ),
    ]
