# Generated by Django 4.2.3 on 2023-09-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookMe', '0005_remove_recipe_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
