# Generated by Django 4.2.3 on 2023-09-05 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookMe', '0006_delete_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tytuł')),
                ('dish_picture', models.ImageField(blank=True, upload_to='dishPics', verbose_name='Zdjęcie potrawy')),
                ('my_rating', models.CharField(choices=[('', 'Wybierz ocenę'), ('rew', 'Rewelacja'), ('nie', 'Nie do powtórzenia'), ('mod', 'Do modyfikacji')], default='', max_length=3, verbose_name='Moja ocena')),
                ('desc_recipe', models.TextField(blank=True, verbose_name='Przepis')),
                ('web_recipe', models.URLField(blank=True, verbose_name='Strona www')),
                ('pic_recipe', models.ImageField(blank=True, upload_to='recipePics', verbose_name='Zdjęcie przepisu')),
                ('comment', models.TextField(blank=True, verbose_name='Moje uwagi')),
                ('main_components', models.TextField(blank=True, verbose_name='Główne składniki')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='cookMe.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['id'], name='cookMe_reci_id_f579ce_idx'), models.Index(fields=['name'], name='cookMe_reci_name_a3d695_idx'), models.Index(fields=['-create_date'], name='cookMe_reci_create__befbda_idx')],
            },
        ),
    ]
