# Generated by Django 4.2.3 on 2023-09-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookMe', '0007_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['title']},
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='cookMe_reci_name_a3d695_idx',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='title',
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['title'], name='cookMe_reci_title_5941a6_idx'),
        ),
    ]
